language: node_js
cache:
  directories:
    - node_modules
branches:
  only:
    - master
node_js:
  - 8
addons:
  chrome: stable
before_install:
  - npm i -g npm@^5.0.0
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
before_script:
  - npm prune
script:
  - npm test
  - npm run build
after_success:
  - npm run report-coverage